openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Monkeys API
  description: Manage a collection of monkeys.
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /monkeys:
    get:
      summary: List all monkeys
      operationId: listMonkeys
      tags:
        - monkeys
      parameters:
        - name: limit
          in: query
          description: How many monkeys to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of monkeys
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Monkeys'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create monkey
      operationId: createMonkey
      tags:
        - monkeys
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /monkeys/{monkeyId}:
    get:
      summary: Info for a specific monkey
      operationId: getMonkey
      tags:
        - monkeys
      parameters:
        - name: monkeyId
          in: path
          description: The id of the monkey to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Monkey'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Monkey:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Monkeys:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Monkey'
