openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Giraffes API
  description: Manage a collection of giraffes.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Giraffe Support Team
    email: giraffes@apigee-apihub-demo.github.io
    url: https://github.com/apigee-apihub-demo/animals
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /giraffes:
    get:
      summary: List all giraffes
      description: List all giraffes
      operationId: listGiraffes
      tags:
        - giraffes
      parameters:
        - name: limit
          in: query
          description: How many giraffes to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of giraffes
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Giraffes'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create giraffe
      description: Create giraffe
      operationId: createGiraffe
      tags:
        - giraffes
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /giraffes/{giraffeId}:
    get:
      summary: Info for a specific giraffe
      description: Info for a specific giraffe
      operationId: getGiraffe
      tags:
        - giraffes
      parameters:
        - name: giraffeId
          in: path
          description: The id of the giraffe to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Giraffe'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Giraffe:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Giraffes:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Giraffe'
tags:
  - name: giraffes
    description: This API is about giraffes.
