apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: fauna-xeruses
  labels:
    apihub-business-unit: fauna
    apihub-kind: enrolled
    apihub-lifecycle: production
    apihub-source: generate-animal-apis
    apihub-style: apihub-openapi
    apihub-target-users: public
    apihub-team: fauna-mammals
    categories: mammals
  annotations:
    apihub-primary-contact: xeruses@apigee-apihub-demo.github.io
    apihub-primary-contact-description: Xerus Support Team
data:
  displayName: Fauna Xeruses API
  description: The Fauna Xeruses API allows users to manage a collection of xeruses.
  recommendedVersion: v1
  recommendedDeployment: prod
  versions:
    - metadata:
        name: v1
        labels:
          apihub-kind: enrolled
          apihub-source: generate-animal-apis
      data:
        displayName: v1
        state: production
        primarySpec: openapi
        specs:
          - metadata:
              name: openapi
              labels:
                apihub-kind: enrolled
                apihub-source: generate-animal-apis
            data:
              filename: openapi.yaml
              mimeType: application/x.openapi+gzip;version=3.0
  deployments:
    - metadata:
        name: prod
        labels:
          apihub-gateway: apihub-google-cloud-apigee
          apihub-kind: enrolled
          apihub-source: generate-animal-apis
        annotations:
          apihub-external-channel-name: Xeruses Developer Portal
      data:
        displayName: Prod
        description: Production deployment
        apiSpecRevision: v1/specs/openapi
        endpointURI: https://xeruses.example.com
        externalChannelURI: https://fauna-portal.example.com/xeruses
        intendedAudience: Public
        accessGuidance: Contact the Xerus Support Team for an API Key.
    - metadata:
        name: test
        labels:
          apihub-gateway: apihub-google-cloud-apigee
          apihub-kind: enrolled
          apihub-source: generate-animal-apis
        annotations:
          apihub-external-channel-name: Xeruses Developer Portal
      data:
        displayName: Test
        description: Test deployment
        apiSpecRevision: v1/specs/openapi
        endpointURI: https://xeruses-test.example.com
        externalChannelURI: https://fauna-portal.example.com/xeruses
        intendedAudience: Internal
        accessGuidance: Contact the Xerus Support Team for an API Key.
  artifacts:
    - kind: ReferenceList
      metadata:
        name: apihub-related
        labels:
          apihub-source: generate-animal-apis
      data:
        displayName: Related Links
        description: ""
        references:
          - id: wikipedia
            displayName: Wikipedia
            category: reference
            resource: ""
            uri: https://en.wikipedia.org/wiki/Xerus
