apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: generate-animal-apis-nc6axd7wrcn4hyvr3ucvmaaubfbr5wb4
  labels:
    apihub-kind: traffic
    apihub-source: generate-animal-apis
data:
  displayName: Traffic Observation 000002
  versions:
    - metadata:
        name: v1
        labels:
          apihub-source: generate-animal-apis
      data:
        displayName: v1
        primarySpec: openapi
        specs:
          - metadata:
              name: openapi
              labels:
                apihub-source: generate-animal-apis
            data:
              filename: openapi.yaml
              mimeType: application/x.openapi+gzip;version=3.0
  deployments:
    - metadata:
        name: location
      data:
        endpointURI: bar.org
  artifacts:
    - kind: ReferenceList
      metadata:
        name: apihub-related
      data:
        displayName: Related Links
        description: Defines a list of related resources
        references:
          - id: fauna-crocodiles
            displayName: Enrolled API
            category: apihub-organization-apis
            resource: projects/apigee-apihub-demo/locations/global/apis/fauna-crocodiles
            uri: ""
