apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: generate-animal-apis-6t4govat3ni6dm6x27y3nedepmeetp36
  labels:
    apihub-kind: traffic
    apihub-lifecycle: observed-traffic
    apihub-source: generate-animal-apis
    apihub-target-users: internal
data:
  displayName: Traffic 000013
  recommendedVersion: v1
  recommendedDeployment: example
  versions:
    - metadata:
        name: v1
        labels:
          apihub-kind: traffic
          apihub-source: generate-animal-apis
      data:
        displayName: v1
        state: observed-traffic
        primarySpec: openapi
        specs:
          - metadata:
              name: openapi
              labels:
                apihub-kind: traffic
                apihub-source: generate-animal-apis
            data:
              filename: openapi.yaml
              mimeType: application/x.openapi+gzip;version=3.0
  deployments:
    - metadata:
        name: example
        labels:
          apihub-gateway: apihub-unmanaged
      data:
        displayName: example
        endpointURI: https://example.com
  artifacts:
    - kind: ReferenceList
      metadata:
        name: apihub-related
      data:
        displayName: Related Links
        description: Defines a list of related resources
        references:
          - id: fauna-nightingales
            displayName: Enrolled API
            category: apihub-organization-apis
            resource: projects/apigee-apihub-demo/locations/global/apis/fauna-nightingales
            uri: ""
