openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Jaguars API
  description: Manage a collection of jaguars.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Jaguar Support Team
    email: jaguars@apigee-apihub-demo.github.io
    url: https://github.com/apigee-apihub-demo/animals
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /jaguars:
    get:
      summary: List all jaguars
      description: List all jaguars
      operationId: listJaguars
      tags:
        - jaguars
      parameters:
        - name: limit
          in: query
          description: How many jaguars to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of jaguars
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jaguars'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create jaguar
      description: Create jaguar
      operationId: createJaguar
      tags:
        - jaguars
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /jaguars/{jaguarId}:
    get:
      summary: Info for a specific jaguar
      description: Info for a specific jaguar
      operationId: getJaguar
      tags:
        - jaguars
      parameters:
        - name: jaguarId
          in: path
          description: The id of the jaguar to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jaguar'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Jaguar:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Jaguars:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Jaguar'
tags:
  - name: jaguars
    description: This API is about jaguars.
