openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Hedgehogs API
  description: Manage a collection of hedgehogs.
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /hedgehogs:
    get:
      summary: List all hedgehogs
      operationId: listHedgehogs
      tags:
        - hedgehogs
      parameters:
        - name: limit
          in: query
          description: How many hedgehogs to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of hedgehogs
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hedgehogs'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create hedgehog
      operationId: createHedgehog
      tags:
        - hedgehogs
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /hedgehogs/{hedgehogId}:
    get:
      summary: Info for a specific hedgehog
      operationId: getHedgehog
      tags:
        - hedgehogs
      parameters:
        - name: hedgehogId
          in: path
          description: The id of the hedgehog to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hedgehog'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Hedgehog:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Hedgehogs:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Hedgehog'
