openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Aardvarks API
  description: Manage a collection of aardvarks.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Aardvark Support Team
    email: aardvarks@apigee-apihub-demo.github.io
    url: https://github.com/apigee-apihub-demo/animals
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /aardvarks:
    get:
      summary: List all aardvarks
      description: List all aardvarks
      operationId: listAardvarks
      tags:
        - aardvarks
      parameters:
        - name: limit
          in: query
          description: How many aardvarks to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of aardvarks
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aardvarks'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create aardvark
      description: Create aardvark
      operationId: createAardvark
      tags:
        - aardvarks
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /aardvarks/{aardvarkId}:
    get:
      summary: Info for a specific aardvark
      description: Info for a specific aardvark
      operationId: getAardvark
      tags:
        - aardvarks
      parameters:
        - name: aardvarkId
          in: path
          description: The id of the aardvark to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aardvark'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Aardvark:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Aardvarks:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Aardvark'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
tags:
  - name: aardvarks
    description: This API is about aardvarks.
