openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Dolphins API
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /dolphins:
    get:
      summary: List all dolphins
      operationId: listDolphins
      tags:
        - dolphins
      parameters:
        - name: limit
          in: query
          description: How many dolphins to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of dolphins
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dolphins'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create dolphin
      operationId: createDolphin
      tags:
        - dolphins
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /dolphins/{dolphinId}:
    get:
      summary: Info for a specific dolphin
      operationId: getDolphin
      tags:
        - dolphins
      parameters:
        - name: dolphinId
          in: path
          description: The id of the dolphin to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dolphin'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Dolphin:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Dolphins:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Dolphin'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
