openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Yaks API
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /yaks:
    get:
      summary: List all yaks
      operationId: listYaks
      tags:
        - yaks
      parameters:
        - name: limit
          in: query
          description: How many yaks to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of yaks
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Yaks'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create yak
      operationId: createYak
      tags:
        - yaks
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /yaks/{yakId}:
    get:
      summary: Info for a specific yak
      operationId: getYak
      tags:
        - yaks
      parameters:
        - name: yakId
          in: path
          description: The id of the yak to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Yak'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Yak:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Yaks:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Yak'
