openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Kangaroos API
  description: Manage a collection of kangaroos.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Kangaroo Support Team
    email: kangaroos@apigee-apihub-demo.github.io
    url: https://github.com/apigee-apihub-demo/animals
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /kangaroos:
    get:
      summary: List all kangaroos
      description: List all kangaroos
      operationId: listKangaroos
      tags:
        - kangaroos
      parameters:
        - name: limit
          in: query
          description: How many kangaroos to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of kangaroos
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kangaroos'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create kangaroo
      description: Create kangaroo
      operationId: createKangaroo
      tags:
        - kangaroos
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /kangaroos/{kangarooId}:
    get:
      summary: Info for a specific kangaroo
      description: Info for a specific kangaroo
      operationId: getKangaroo
      tags:
        - kangaroos
      parameters:
        - name: kangarooId
          in: path
          description: The id of the kangaroo to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kangaroo'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Kangaroo:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Kangaroos:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Kangaroo'
tags:
  - name: kangaroos
    description: This API is about kangaroos.
