openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Iguanas API
  description: Manage a collection of iguanas.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Iguana Support Team
    email: iguanas@apigee-apihub-demo.github.io
    url: https://github.com/apigee-apihub-demo/animals
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /iguanas:
    get:
      summary: List all iguanas
      description: List all iguanas
      operationId: listIguanas
      tags:
        - iguanas
      parameters:
        - name: limit
          in: query
          description: How many iguanas to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of iguanas
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Iguanas'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create iguana
      description: Create iguana
      operationId: createIguana
      tags:
        - iguanas
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /iguanas/{iguanaId}:
    get:
      summary: Info for a specific iguana
      description: Info for a specific iguana
      operationId: getIguana
      tags:
        - iguanas
      parameters:
        - name: iguanaId
          in: path
          description: The id of the iguana to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Iguana'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Iguana:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Iguanas:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Iguana'
tags:
  - name: iguanas
    description: This API is about iguanas.
