openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Porcupines API
  description: Manage a collection of porcupines.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Porcupine Support Team
    email: porcupines@apigee-apihub-demo.github.io
    url: https://github.com/apigee-apihub-demo/animals
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /porcupines:
    get:
      summary: List all porcupines
      description: List all porcupines
      operationId: listPorcupines
      tags:
        - porcupines
      parameters:
        - name: limit
          in: query
          description: How many porcupines to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of porcupines
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Porcupines'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create porcupine
      description: Create porcupine
      operationId: createPorcupine
      tags:
        - porcupines
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /porcupines/{porcupineId}:
    get:
      summary: Info for a specific porcupine
      description: Info for a specific porcupine
      operationId: getPorcupine
      tags:
        - porcupines
      parameters:
        - name: porcupineId
          in: path
          description: The id of the porcupine to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Porcupine'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Porcupine:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Porcupines:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Porcupine'
tags:
  - name: porcupines
    description: This API is about porcupines.
