openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Zebras API
  description: Manage a collection of zebras.
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /zebras:
    get:
      summary: List all zebras
      operationId: listZebras
      tags:
        - zebras
      parameters:
        - name: limit
          in: query
          description: How many zebras to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of zebras
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zebras'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create zebra
      operationId: createZebra
      tags:
        - zebras
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /zebras/{zebraId}:
    get:
      summary: Info for a specific zebra
      operationId: getZebra
      tags:
        - zebras
      parameters:
        - name: zebraId
          in: path
          description: The id of the zebra to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zebra'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Zebra:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Zebras:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Zebra'
