apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: fauna-whales
  labels:
    apihub-business-unit: fauna
    apihub-lifecycle: production
    apihub-style: apihub-openapi
    apihub-target-users: public
    apihub-team: fauna-mammals
    categories: mammals
    provider: fauna
    source: generate-animal-apis
    updated: "2023-06-07"
  annotations:
    apihub-primary-contact: whales@apigee-apihub-demo.github.io
    apihub-primary-contact-description: Whale Support Team
    legs: "0"
    lifespan: 50-80 years
    weight: 150-200 tons
data:
  displayName: Fauna Whales API
  description: The Fauna Whales API allows users to manage a collection of whales.
  recommendedVersion: v1
  versions:
    - metadata:
        name: v1
        labels:
          source: generate-animal-apis
          updated: "2023-06-07"
      data:
        displayName: v1
        state: production
        primarySpec: openapi
        specs:
          - metadata:
              name: openapi
              labels:
                source: generate-animal-apis
                updated: "2023-06-07"
            data:
              filename: openapi.yaml
              mimeType: application/x.openapi+gzip;version=3.0
  artifacts:
    - kind: ReferenceList
      metadata:
        name: apihub-related
        labels:
          source: generate-animal-apis
          updated: "2023-06-07"
      data:
        displayName: Related Links
        description: ""
        references:
          - id: wikipedia
            displayName: Wikipedia
            category: reference
            resource: ""
            uri: https://en.wikipedia.org/wiki/Whale
