apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: fauna-nightingales
  labels:
    apihub-business-unit: fauna
    apihub-kind: enrolled
    apihub-lifecycle: production
    apihub-source: generate-animal-apis
    apihub-style: apihub-openapi
    apihub-target-users: public
    apihub-team: fauna-birds
    categories: birds
  annotations:
    apihub-primary-contact: nightingales@apigee-apihub-demo.github.io
    apihub-primary-contact-description: Nightingale Support Team
data:
  displayName: Fauna Nightingales API
  description: The Fauna Nightingales API allows users to manage a collection of nightingales.
  recommendedVersion: v1
  versions:
    - metadata:
        name: v1
        labels:
          apihub-source: generate-animal-apis
      data:
        displayName: v1
        state: production
        primarySpec: openapi
        specs:
          - metadata:
              name: openapi
              labels:
                apihub-source: generate-animal-apis
            data:
              filename: openapi.yaml
              mimeType: application/x.openapi+gzip;version=3.0
  artifacts:
    - kind: ReferenceList
      metadata:
        name: apihub-related
        labels:
          apihub-source: generate-animal-apis
      data:
        displayName: Related Links
        description: ""
        references:
          - id: wikipedia
            displayName: Wikipedia
            category: reference
            resource: ""
            uri: https://en.wikipedia.org/wiki/Nightingale
