openapi: 3.0.0
info:
  version: 1.0.0
  title: Fauna Crocodiles API
  description: Manage a collection of crocodiles.
servers:
  - url: https://apigee-apihub-demo.github.io
paths:
  /crocodiles:
    get:
      summary: List all crocodiles
      operationId: listCrocodiles
      tags:
        - crocodiles
      parameters:
        - name: limit
          in: query
          description: How many crocodiles to return at one time (max 100)
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of crocodiles
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Crocodiles'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create crocodile
      operationId: createCrocodile
      tags:
        - crocodiles
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /crocodiles/{crocodileId}:
    get:
      summary: Info for a specific crocodile
      operationId: getCrocodile
      tags:
        - crocodiles
      parameters:
        - name: crocodileId
          in: path
          description: The id of the crocodile to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Crocodile'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Crocodile:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Crocodiles:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Crocodile'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
